baseURL = "http://example.org/"
languageCode = "en-us"
title = "Space Governance"
disablePathToLower = true
enableGitInfo = true

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
name = "Explainer"
url = "/explainer/"
weight = 1

[[menu.main]]
name = "Resources"
url = "/resources/"
weight = 2

[[menu.main]]
name = "Research Agenda"
url = "/research-agenda/"
weight = 3

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 4