baseURL = "http://spacefuturesinitiative.org/"
languageCode = "en-us"
title = "Space Futures Initiative"
disablePathToLower = true
enableGitInfo = true

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "Research"
url = "/research/"
weight = 2

[[menu.main]]
name = "Opportunities"
url = "/opportunities/"
weight = 3

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 4