baseURL = "http://spacefuturesinitiative.org/"
languageCode = "en-us"
title = "Space Futures Initiative"
disablePathToLower = true
enableGitInfo = true

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1
  [[menu.main]]
  name = "Team"
  url = "/team/"
  weight = 1
  parent = "about"

[[menu.main]]
identifier = "research"
name = "Research"
url = "/research/"
weight = 2
  [[menu.main]]
  name = "Research Agenda"
  url = "/research-agenda/"
  weight = 1
  parent = "research"
  [[menu.main]]
  name = "Explainer"
  url = "/explainer/"
  weight = 2
  parent = "research"
  [[menu.main]]
  name = "Resources"
  url = "/resources/"
  weight = 3
  parent = "research"
  [[menu.main]]
  name = "Papers"
  url = "/papers/"
  weight = 4
  parent = "research"
  

[[menu.main]]
identifier = "opportunities"
name = "Opportunities"
url = "/opportunities/"
weight = 3

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 4